AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4
Gemspec/RequiredRubyVersion:
  Enabled: false
Metrics/AbcSize:
  Exclude:
    - test/**/*
Metrics/BlockLength:
  Exclude:
    - lib/peddler/marketplace.rb
Metrics/ClassLength:
  Exclude:
    - lib/peddler/client.rb
    - lib/mws/**/client.rb
    - test/**/*
Lint/HandleExceptions:
  Exclude:
    - test/**/*
Metrics/LineLength:
  Exclude:
    - test/**/*
  IgnoredPatterns: ['\A\s*#']
Metrics/MethodLength:
  Exclude:
    - test/**/*
    - lib/mws/**/client.rb
Metrics/ParameterLists:
  Exclude:
    - lib/mws/**/client.rb
Naming/AccessorMethodName:
  Exclude:
    - lib/mws/**/client.rb
Performance/RegexpMatch:
  Enabled: false # doesn't work below 2.4
Style/Documentation:
  Exclude:
    - test/**/*
