AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4
Metrics/AbcSize:
  Exclude:
    - test/**/*
Metrics/ClassLength:
  Exclude:
    - lib/peddler/client.rb
    - lib/mws/**/client.rb
    - test/**/*
Lint/HandleExceptions:
  Exclude:
    - test/**/*
Metrics/LineLength:
  Exclude:
    - test/**/*
Metrics/MethodLength:
  Exclude:
    - test/**/*
    - lib/mws/**/client.rb
Metrics/ParameterLists:
  Exclude:
    - lib/mws/**/client.rb
Naming/AccessorMethodName:
  Exclude:
    - lib/mws/**/client.rb
Performance/RegexpMatch:
  Enabled: false # doesn't work below 2.4
Performance/UnfreezeString:
  Enabled: false # doesn't work below 2.3
Style/Documentation:
  Exclude:
    - test/**/*
Style/NumericPredicate:
  Enabled: false # doesn't work below 2.3
Style/SafeNavigation:
  Enabled: false # doesn't work below 2.3
