AllCops:
  Exclude:
    - 'test/helper.rb'
AbcSize:
  Exclude:
    - 'test/**/*'
AccessorMethodName:
  Exclude:
    - 'lib/mws/**/client.rb'
ClassLength:
  Enabled: false
LineLength:
  Exclude:
    - 'test/**/*'
    - 'lib/mws/**/client.rb'
MethodLength:
  Exclude:
    - 'test/**/*'
    - 'lib/mws/**/client.rb'
MultilineMethodCallIndentation:
  EnforcedStyle: indented
ParameterLists:
  Exclude:
    - 'lib/mws/**/client.rb'
