AllCops:
  Exclude:
    - 'test/helper.rb'
AbcSize:
  Exclude:
    - 'test/**/*'
AccessorMethodName:
  Exclude:
    - 'lib/mws/**/client.rb'
ClassLength:
  Enabled: false
Documentation:
  Exclude:
    - 'test/**/*'
DotPosition:
  EnforcedStyle: leading
FileName:
  Exclude:
    - Appraisals
GlobalVars:
  Exclude:
    - 'test/**/*'
HandleExceptions:
  Exclude:
    - 'test/**/*'
GuardClause:
  Enabled: false
LineLength:
  Exclude:
    - 'test/**/*'
    - 'lib/mws/**/client.rb'
MethodLength:
  Exclude:
    - 'test/**/*'
    - 'lib/mws/**/client.rb'
MultilineMethodCallIndentation:
  EnforcedStyle: indented
ParameterLists:
  Exclude:
    - 'lib/mws/**/client.rb'
StringLiterals:
  EnforcedStyle: single_quotes
