Layout/LineLength:
  Exclude:
    - "test/**/*"
  IgnoredPatterns: ['\A\s*#']
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
  Exclude:
    - "test/**/*"
Metrics/AbcSize:
  Exclude:
    - "test/**/*"
Metrics/ClassLength:
  Exclude:
    - "lib/mws/**/client.rb"
    - "test/**/*"
Metrics/MethodLength:
  Exclude:
    - "lib/mws/**/client.rb"
    - "test/**/*"
Metrics/ParameterLists:
  Exclude:
    - "lib/mws/**/client.rb"
Naming/AccessorMethodName:
  Exclude:
    - "lib/mws/**/client.rb"
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
