AllCops:
  Exclude:
    - 'test/helper.rb'
AccessorMethodName:
  Exclude:
    - 'lib/mws/**/client.rb'
ClassLength:
  Enabled: false
LineLength:
  Exclude:
    - 'test/**/*'
    - 'lib/mws/**/*'
MethodLength:
  Exclude:
    - 'test/**/*'
    - 'lib/mws/**/*'
MultilineMethodCallIndentation:
  EnforcedStyle: indented
ParameterLists:
  Exclude:
    - 'lib/mws/**/*'
