after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
before_install:
  - gem update --system
  - gem install bundler
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
env:
  global:
    - AWS_ACCESS_KEY_ID=foo
    - AWS_SECRET_ACCESS_KEY=bar
    - CC_TEST_REPORTER_ID=738ee95086106a9011b10dd006ac5e0d74541774c8bb6d9e5ceb705c01115afa
gemfile:
  - gemfiles/libxml.gemfile
  - gemfiles/oga.gemfile
  - gemfiles/ox.gemfile
  - gemfiles/nokogiri.gemfile
  - gemfiles/rexml.gemfile
  - gemfiles/jeff_1.gemfile
  - gemfiles/jeff_2.gemfile
language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: jruby-9000
      gemfile: gemfiles/ox.gemfile
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - jruby-9000
  - ruby-head
sudo: false
