addons:
  code_climate:
    repo_token: 738ee95086106a9011b10dd006ac5e0d74541774c8bb6d9e5ceb705c01115afa
after_success:
  - bundle exec codeclimate-test-reporter
before_install:
  - gem update --system
  - gem install bundler
env:
  global:
    - AWS_ACCESS_KEY_ID=foo
    - AWS_SECRET_ACCESS_KEY=bar
gemfile:
  - gemfiles/libxml.gemfile
  - gemfiles/oga.gemfile
  - gemfiles/ox.gemfile
  - gemfiles/nokogiri.gemfile
  - gemfiles/rexml.gemfile
  - gemfiles/jeff_1.gemfile
  - gemfiles/jeff_2.gemfile
language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: jruby-9000
      gemfile: gemfiles/ox.gemfile
rvm:
  - 2.1
  - 2.2
  - 2.3.3
  - 2.4.0
  - jruby-9000
  - ruby-head
sudo: false
