language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - jruby-19mode
  - ruby-head
  - jruby-head
env:
  global:
    - AWS_ACCESS_KEY_ID=foo
    - AWS_SECRET_ACCESS_KEY=bar
    - JRUBY_OPTS=--2.0
matrix:
  allow_failures:
    - rvm:
      - ruby-head
      - jruby-head
