version: 2.1

defaults: &defaults
  environment:
    AWS_ACCESS_KEY_ID: secret
    AWS_SECRET_ACCESS_KEY: secret
  steps:
    - checkout
    - run: bundle install
    - run: bundle exec appraisal install
    - run: bundle exec appraisal rake test

jobs:
  ruby-24:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.4
  ruby-25:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.5
  ruby-26:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.6
  rubocop:
    docker:
      - image: circleci/ruby:2.4
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rake rubocop

workflows:
  version: 2
  build:
    jobs:
      - ruby-24
      - ruby-25
      - ruby-26
      - rubocop
